# Generated by Django 3.1.7 on 2021-04-06 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='name')),
                ('task_text', models.TextField(verbose_name='text')),
            ],
            options={
                'ordering': ('task_name',),
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='homeworks/files/%Y/%m/%d/')),
                ('homework_status', models.CharField(choices=[('RE', 'Received'), ('DO', 'Done'), ('GR', 'Graded')], default='RE', max_length=16)),
                ('mark', models.FloatField(blank=True, null=True)),
                ('mark_description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.profile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'ordering': ('profile', 'task'),
            },
        ),
    ]
